# Generated by Django 3.0.8 on 2020-09-02 10:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200902_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default=datetime.datetime(2020, 9, 2, 10, 35, 32, 961892, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
    ]
