# Generated by Django 3.0.8 on 2020-09-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200902_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic/'),
        ),
    ]
