# Generated by Django 3.0.8 on 2020-09-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='profilepic/default.png', null=True, upload_to='profilepic/'),
        ),
    ]
