# Generated by Django 3.0.8 on 2020-09-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likes',
        ),
    ]
