# Generated by Django 3.0.8 on 2020-09-14 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_liked_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='liked_videos',
        ),
    ]
