# Generated by Django 3.0.8 on 2020-09-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='liked_videos',
            field=models.ManyToManyField(null=True, to='core.Video'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
