# Generated by Django 3.0.8 on 2020-09-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200914_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='likers',
        ),
        migrations.AddField(
            model_name='video',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
