# Generated by Django 3.0.8 on 2020-09-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist',
            new_name='videos',
        ),
        migrations.AddField(
            model_name='playlist',
            name='name',
            field=models.CharField(default='new playlist', max_length=50),
        ),
    ]
