# Generated by Django 3.0.8 on 2020-09-22 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200922_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='name',
            new_name='playlist_name',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='videos',
            new_name='playlist_videos',
        ),
        migrations.AddField(
            model_name='playlist',
            name='playlist_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
