# Generated by Django 3.0.8 on 2020-09-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_subscribed_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_playlists',
            field=models.ManyToManyField(to='core.Playlist'),
        ),
    ]
