# Generated by Django 3.0.8 on 2020-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viewed_videos',
            field=models.ManyToManyField(related_name='user_viewed_videos', to='core.Video'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_videos',
            field=models.ManyToManyField(related_name='user_liked_videos', to='core.Video'),
        ),
    ]
